language: node_js
node_js:
  - 7
  - 6
  - 5
  - 4
scripts:
  - npm run test
  - npm run lint
  - npm run build
after_success:
  - rm -fr ./dist && NODE_ENV=production npm run build && semantic-release pre && npm publish && semantic-release post
notifications:
  email: false
sudo: false
